alias aptcl='sudo apt-get clean'
alias aptins='sudo apt-get install'
alias aptpurge='sudo apt-get --purge remove'
alias aptremove='sudo apt-get remove'
alias autocl='sudo apt-get autoclean'
alias autorm='sudo apt-get autoremove'
alias cd='clear && cd $1'
alias clock='date +"%r"'
alias col='clear ; colors ; txtcolor'
alias cview='colorview'
alias dcalc='xsel -o | dmenu -p Calculate: | xargs echo | bc 2>&1 | dmenu -p Answer: | xsel -i'
alias dir='dir --color=auto'
alias downup='sudo service networking restart'
alias dupg='sudo apt-get dist-upgrade'
alias egrep='egrep --color=auto'
alias e='nano  $1'
alias fgrep='fgrep --color=auto'
alias free='free -h'
alias grep='grep --color=auto'
alias hc='herbstclient'
alias herbdetmon='herbstclient detect_monitors'
alias herbhdmi='herbstclient set_monitors 1366x768+0+0 1280x720+1366+0 && xrandr --output HDMI1 --right-of LVDS1 --mode 1280x720'
alias h='htop'
alias l1='ls -1 --group-directories-first --color=auto'
alias lal='ls -Al --group-directories-first'
alias la='ls -A --group-directories-first'
alias lc='clear && ls -l --group-directories-first && echo -e \\n[$PWD] && echo'
alias ll='ls -l --group-directories-first'
alias l='ls -l --group-directories-first'
alias ls='ls --group-directories-first --color=auto'
alias m='albumart ; ncmpcpp'
alias mexh='udisksctl mount --block-device /dev/sdb1'
alias mm='pmount /dev/sdb1 && cd /media/sdb1'
alias netdown='sudo systemctl stop networking.service'
alias netrestart='sudo systemctl restart networking.service'
alias netup='sudo systemctl start networking.service'
alias obexit='openbox --exit'
alias obreconfig='openbox --reconfigure'
alias obrestart='openbox --restart'
alias open='xdg-open $1'
alias pd='pwd && ls -1l'
alias pof='poweroff'
alias pser='clear ; free ; srvstaton ; pstree'
alias psm='sudo psmem'
alias rbt='reboot'
alias r='ranger'
alias sl='sl -alFe'
alias srvstatoff='sudo service --status-all | grep -w -'
alias srvstaton='sudo service --status-all | grep +'
alias startvbox='sudo systemctl start virtualbox'
alias twmhdmi='xrandr --output HDMI1 --mode 1280x720 --below LVDS1'
alias twmrc='sudo nano /usr/lib/X11/twm/system.twmrc-menu'
alias um='cd && pumount /dev/sdb1'
alias umexh='udisksctl unmount --block-device /dev/sdb1'
alias up='cd "$(ls -d */ | dmenu -fn glisp -nb "#100" -nf "#b9c0af" -sb "#000" -sf "#afff2f" -i)"'
alias upd='sudo apt-get update'
alias upg='sudo apt-get upgrade'
alias v='alsamixer'
alias vdir='vdir --color=auto'
alias xmerge='xrdb -merge .Xresources'
alias x='startx'
