#!/bin/bash
#     __              __         __  __      ______                   
#    / /_  ___  _____/ /_  _____/ /_/ /_  __/ __/ /__      ______ ___ 
#   / __ \/ _ \/ ___/ __ \/ ___/ __/ / / / / /_/ __/ | /| / / __ `__ \
#  / / / /  __/ /  / /_/ (__  ) /_/ / /_/ / __/ /_ | |/ |/ / / / / / /
# /_/ /_/\___/_/  /_.___/____/\__/_/\__,_/_/  \__/ |__/|__/_/ /_/ /_/ 
#         

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4    # Use alt as the main modifier

hc keybind $Mod-q spawn herbdmenu
hc keybind $Mod-Shift-c close
hc keybind $Mod-d spawn dmenu-bind.sh
hc keybind $Mod-Return spawn x-terminal-emulator
hc keybind $Mod-space spawn termopen

# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Alt-h    shift left
hc keybind $Mod-Alt-j    shift down
hc keybind $Mod-Alt-k    shift up
hc keybind $Mod-Alt-l    shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.02
hc keybind $Mod-Shift-h       resize left +$resizestep
hc keybind $Mod-Shift-j       resize down +$resizestep
hc keybind $Mod-Shift-k       resize up +$resizestep
hc keybind $Mod-Shift-l       resize right +$resizestep

# tags
tag_names=( A B )
tag_keys=( {1..2} 0 )
0
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# eayouting
hc keybind $Mod-w remove
hc keybind $Mod-c cycle_layout 1
hc keybind $Mod-r rotate 
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
#hc keybind $Mod-BackSpacb   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-n cycle
#hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# Layer 1
#hsetroot -fill /home/gako/med/img/wallpaper/gako-kerotan-c5b994.png
hsetroot -solid "#9e7960"
#compton -b
hc set frame_gap 0

# Layer 2
hc set frame_border_active_color '#ff0000' 
hc set frame_border_normal_color '#9e7960'
hc set frame_border_width 0

# Layer 3
hc set frame_bg_active_color     '#9e7960'
hc set frame_bg_normal_color     '#9e7960'
hc set window_gap 0
hc set frame_padding 0
hc set always_show_frame 0
hc set frame_bg_transparent 0
hc set frame_transparent_width 0
hc set frame_active_opacity 100
hc set frame_normal_opacity 0

# Layer 4
#hc set window_border_active_color '#c5b994'
hc set window_border_active_color '#c0ba9d'
hc set window_border_normal_color '#9e7960'
hc set window_border_inner_color  '#9e7960'
hc set window_border_width 6
hc set window_border_inner_width 5

# Float
hc attr theme.active.outer_color '#403a30'
hc attr theme.normal.outer_color '#c5b994'
hc attr theme.floating.outer_width 10
hc attr theme.floating.border_width 5
hc set raise_on_focus 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1280x1024+0+0 1280x1024+1280+0
#hc set_monitors 1366x768+0+0 1280x720+1366+0 
# or simply:
#hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
